rptts:../src/main.cpp ../src/solve.cpp ../src/solve.h ../src/io.cpp ../src/io.h ../src/matching.cpp ../src/matching.h
	g++ -std=c++11 -o rptts ../src/io.cpp ../src/matching.cpp ../src/main.cpp ../src/solve.cpp ../../../../essentials/config/config.o ../../../../essentials/string-helper/string_helper.o 

clean:
	rm -f matching.o main.o io.o solve.o