all:
	g++ aperiodic.h aperiodic.cpp main.cpp ../../../essentials/config/config.o ../../../essentials/string-helper/string_helper.o -I../../../../libs/goblin/include -L../../../../libs/goblin/lib -lgoblin -o aperiodic -O3
