include ../../essentials/settings/Makefile.env
Conv_Game: ../../essentials/config/config.o ../../essentials/string-helper/string_helper.o
SolConv: ../../essentials/config/config.o ../../essentials/string-helper/string_helper.o

clean:
	rm -f SolConv Conv_Game
