networksimplex: ../src/main.cpp ../src/modulo_network_simplex.cpp
	g++ -I../include -O3 -Wno-deprecated -I"../../../../../libs/boost/include" -I"../../../../../libs/goblin/include" -L"../../../../../libs/goblin/lib" ../src/main.cpp ../src/modulo_network_simplex.cpp -lgoblin ../../../../essentials/config/config.o ../../../../essentials/string-helper/string_helper.o -o networksimplex

