networksimplex: ../src/main.cpp ../src/modulo_network_simplex.cpp
	g++ -I../include -O3 -Wno-deprecated -I"../../../../../libs/boost/include" ../src/main.cpp ../src/modulo_network_simplex.cpp ../../../../essentials/config/config.o ../../../../essentials/string-helper/string_helper.o -o networksimplex -I"${GUROBI_HOME}/include" -L"${GUROBI_HOME}/lib" -lgurobi_c++ -lgurobi90 -lm
