matching_merge:../src/matching_merge.cpp ../src/matching_merge.h ../src/main.cpp
	g++ -std=c++11 -o matching_merge ../src/matching_merge.cpp ../src/main.cpp ../../../../essentials/config/config.o ../../../../essentials/string-helper/string_helper.o

clean:
	rm -f matching_merge.o main.o
