conprop: conprop.cpp conprop.h main.cpp
	g++ -o conprop conprop.cpp main.cpp ../../../../essentials/config/config.o ../../../../essentials/string-helper/string_helper.o -O3

clean:
	rm -f conprop.o main.o
